//===- pdll_strength_demo.cpp - Demo 2: muli(x,2) -> addi(x,x) -----------===//
//
// Demonstrates PDLL native C++ constraints [{ }] and operand capture.
//
// Builds this IR:
//   func.func @strength_test() -> i32 {
//     %x  = arith.constant 5 : i32   <- input operand for muli
//     %c2 = arith.constant 2 : i32   <- isConstantTwo constraint checks this
//     %r  = arith.muli %x, %c2 : i32 <- StrengthReduceMulByTwo pattern fires
//     return %r : i32
//   }
//
// After PDLL pattern (StrengthReduceMulByTwo in strength_patterns.pdll):
//   func.func @strength_test() -> i32 {
//     %x = arith.constant 5 : i32
//     %r = arith.addi %x, %x : i32   <- muli replaced with addi(x, x)
//     return %r : i32
//   }
//
// The native constraint [{ constOp.value() == 2 }] ensures the pattern only
// fires when the multiplier is exactly 2 — not for muli(x, 3) etc.
//===----------------------------------------------------------------------===//

#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/PDL/IR/PDL.h"
#include "mlir/Dialect/PDLInterp/IR/PDLInterp.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Rewrite/FrozenRewritePatternSet.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/Support/raw_ostream.h"

// Generated by add_mlir_pdll_library (CMakeLists.txt: PDLLStrengthPatternsIncGen)
#include "StrengthPatterns.h.inc"

using namespace mlir;

int main() {
  MLIRContext ctx;
  ctx.loadDialect<arith::ArithDialect, func::FuncDialect,
                  pdl::PDLDialect, pdl_interp::PDLInterpDialect>();

  OpBuilder builder(&ctx);
  auto loc = builder.getUnknownLoc();

  auto module = ModuleOp::create(builder, loc);
  builder.setInsertionPointToEnd(module.getBody());

  auto i32 = builder.getI32Type();
  auto funcType = builder.getFunctionType({}, {i32});
  auto func = func::FuncOp::create(builder, loc, "strength_test", funcType);
  auto *block = func.addEntryBlock();
  builder.setInsertionPointToStart(block);

  // %x  = arith.constant 5 : i32  (the "input" that isConstantTwo does NOT match)
  auto x = arith::ConstantIntOp::create(builder, loc, 5, 32);
  // %c2 = arith.constant 2 : i32  (isConstantTwo fires: value == 2)
  auto c2 = arith::ConstantIntOp::create(builder, loc, 2, 32);
  // %r  = arith.muli %x, %c2 : i32  <- pattern matches this
  auto mul = arith::MulIOp::create(builder, loc, x.getResult(), c2.getResult());
  // return %r : i32
  func::ReturnOp::create(builder, loc, ValueRange{mul.getResult()});

  llvm::outs() << "=== Before PDLL patterns ===\n";
  module.print(llvm::outs());
  llvm::outs() << "\n";

  // Apply PDLL patterns: StrengthReduceMulByTwo replaces muli(x,2) with addi(x,x)
  RewritePatternSet patterns(&ctx);
  populateGeneratedPDLLPatterns(patterns);
  FrozenRewritePatternSet frozen(std::move(patterns));
  if (failed(applyPatternsGreedily(func, frozen))) {
    llvm::errs() << "Pattern application failed\n";
    return 1;
  }

  llvm::outs() << "=== After PDLL patterns (muli(x,2) -> addi(x,x)) ===\n";
  module.print(llvm::outs());
  llvm::outs() << "\n";
  return 0;
}
