//===- pdll_dce_demo.cpp - Demo 3: Erase dead arith.constant via PDLL -----===//
//
// Demonstrates PDLL erase action with a native use_empty() constraint.
//
// Builds this IR:
//   func.func @dce_test() {
//     %c10 = arith.constant 10 : i32   <- dead: result never used
//     %c20 = arith.constant 20 : i32   <- dead: result never used
//     return                            <- zero operands confirms no live uses
//   }
//
// After PDLL pattern (EraseDeadConstant in dce_patterns.pdll):
//   func.func @dce_test() {
//     return   <- both dead constants erased
//   }
//
// CRITICAL: The two constants' results are never passed to any op or
// terminator. The zero-operand return ensures they are always dead.
// The IsUnused constraint guards erase — RewriterBase::eraseOp() asserts
// use_empty() internally, so the constraint makes the safety explicit.
//===----------------------------------------------------------------------===//

#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/PDL/IR/PDL.h"
#include "mlir/Dialect/PDLInterp/IR/PDLInterp.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Rewrite/FrozenRewritePatternSet.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/Support/raw_ostream.h"

// Generated by add_mlir_pdll_library (CMakeLists.txt: PDLLDCEPatternsIncGen)
#include "DCEPatterns.h.inc"

using namespace mlir;

int main() {
  MLIRContext ctx;
  ctx.loadDialect<arith::ArithDialect, func::FuncDialect,
                  pdl::PDLDialect, pdl_interp::PDLInterpDialect>();

  OpBuilder builder(&ctx);
  auto loc = builder.getUnknownLoc();

  auto module = ModuleOp::create(builder, loc);
  builder.setInsertionPointToEnd(module.getBody());

  // void function — zero-operand return guarantees no constant result is live
  auto funcType = builder.getFunctionType({}, {});
  auto func = func::FuncOp::create(builder, loc, "dce_test", funcType);
  auto *block = func.addEntryBlock();
  builder.setInsertionPointToStart(block);

  // Two dead constants — results intentionally NOT used anywhere.
  // DO NOT pass these to any op or to the return terminator.
  arith::ConstantIntOp::create(builder, loc, 10, 32);  // dead
  arith::ConstantIntOp::create(builder, loc, 20, 32);  // dead

  // Zero-operand return — confirms the two constants have no uses.
  func::ReturnOp::create(builder, loc, ValueRange{});

  llvm::outs() << "=== Before PDLL patterns (two dead constants) ===\n";
  module.print(llvm::outs());
  llvm::outs() << "\n";

  // Apply PDLL patterns: EraseDeadConstant erases both unused constants
  RewritePatternSet patterns(&ctx);
  populateGeneratedPDLLPatterns(patterns);
  FrozenRewritePatternSet frozen(std::move(patterns));
  if (failed(applyPatternsGreedily(func, frozen))) {
    llvm::errs() << "Pattern application failed\n";
    return 1;
  }

  llvm::outs() << "=== After PDLL patterns (dead constants erased) ===\n";
  module.print(llvm::outs());
  llvm::outs() << "\n";
  return 0;
}
