//===- pdll_fold_demo.cpp - Demo 1: Pattern match addi(const,const) -------===//
//
// Demonstrates PDLL structural pattern matching and the 'replace' action.
//
// Builds this IR:
//   func.func @fold_test() -> i32 {
//     %c3 = arith.constant 3 : i32
//     %c4 = arith.constant 4 : i32
//     %r  = arith.addi %c3, %c4 : i32   <- FoldConstantAdd pattern fires here
//     return %r : i32
//   }
//
// After PDLL pattern (FoldConstantAdd in fold_patterns.pdll):
//   The addi is replaced with its LHS operand (%c3). The function returns %c3.
//   %c4 becomes dead and the greedy rewriter may eliminate it.
//
// How PDLL integrates with C++:
//   1. fold_patterns.pdll is compiled by mlir-pdll to FoldPatterns.h.inc
//   2. #include "FoldPatterns.h.inc" exposes populateGeneratedPDLLPatterns()
//   3. populateGeneratedPDLLPatterns() registers the patterns into a
//      RewritePatternSet, which applyPatternsGreedily then applies.
//===----------------------------------------------------------------------===//

#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/PDL/IR/PDL.h"
#include "mlir/Dialect/PDLInterp/IR/PDLInterp.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Rewrite/FrozenRewritePatternSet.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/Support/raw_ostream.h"

// Generated by add_mlir_pdll_library (CMakeLists.txt: PDLLFoldPatternsIncGen)
// Exposes: void populateGeneratedPDLLPatterns(RewritePatternSet &patterns)
#include "FoldPatterns.h.inc"

using namespace mlir;

int main() {
  MLIRContext ctx;
  ctx.loadDialect<arith::ArithDialect, func::FuncDialect,
                  pdl::PDLDialect, pdl_interp::PDLInterpDialect>();

  OpBuilder builder(&ctx);
  auto loc = builder.getUnknownLoc();

  // Build module and function returning i32
  auto module = ModuleOp::create(builder, loc);
  builder.setInsertionPointToEnd(module.getBody());

  auto i32 = builder.getI32Type();
  auto funcType = builder.getFunctionType({}, {i32});
  auto func = func::FuncOp::create(builder, loc, "fold_test", funcType);
  auto *block = func.addEntryBlock();
  builder.setInsertionPointToStart(block);

  // %c3 = arith.constant 3 : i32
  auto c3 = arith::ConstantIntOp::create(builder, loc, 3, 32);
  // %c4 = arith.constant 4 : i32
  auto c4 = arith::ConstantIntOp::create(builder, loc, 4, 32);
  // %r  = arith.addi %c3, %c4 : i32
  auto add = arith::AddIOp::create(builder, loc, c3.getResult(), c4.getResult());
  // return %r : i32
  func::ReturnOp::create(builder, loc, ValueRange{add.getResult()});

  llvm::outs() << "=== Before PDLL patterns ===\n";
  module.print(llvm::outs());
  llvm::outs() << "\n";

  // Apply PDLL patterns: FoldConstantAdd replaces addi with lhs constant
  RewritePatternSet patterns(&ctx);
  populateGeneratedPDLLPatterns(patterns);
  FrozenRewritePatternSet frozen(std::move(patterns));
  if (failed(applyPatternsGreedily(func, frozen))) {
    llvm::errs() << "Pattern application failed\n";
    return 1;
  }

  llvm::outs() << "=== After PDLL patterns (addi replaced with lhs constant) ===\n";
  module.print(llvm::outs());
  llvm::outs() << "\n";
  return 0;
}
